#!/usr/bin/php
<?php

require_once("vendor/autoload.php");

use \Segura\CLI;

CLI\Toolkit::Factory()
    ->addMenu(
        CLI\MenuItem::Create("time", "Time", function(){
            echo date("Y-m-d H:i:s")."\n";
        })
    )
    ->addMenu(
        CLI\SubMenu::Create("SubMenu")
            ->addMenu()
    );

$cli->run();